import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Navbar
    'nav.pricing': 'Preços',
    'nav.blog': 'Blog',
    'nav.download': 'Download',
    'nav.contact': 'Contacto',
    'nav.getStarted': 'Começar',
    'nav.guide': 'Guia Rápido',

    // Hero
    'hero.badge': 'Solução de Selo Digital',
    'hero.title': 'Sele o seu negócio',
    'hero.subtitle': 'Selo digital, pronto em segundos',
    'hero.benefit1': 'Selos digitais juridicamente vinculantes',
    'hero.benefit2': 'Designs personalizados e modelos de selos',
    'hero.benefit3': 'Armazenamento seguro na nuvem para todos os documentos',
    'hero.cta.start': 'Experimentar já',
    'hero.cta.download': 'Baixar App',
    'hero.stats': 'Documentos Selados Diariamente',

    // Features
    'features.title': 'Tudo o Que Você Precisa para Selar Digitalmente',
    'features.subtitle': 'Recursos poderosos projetados para otimizar o seu programa de fidelização e aumentar o envolvimento dos clientes.',
    'features.custom.title': 'Selos digitais em segundos',
    'features.custom.desc': 'O cliente mostra o QR no telemóvel, o colaborador aponta a câmara e o selo é registado automaticamente.',
    'features.instant.title': 'Várias localizações e grupos',
    'features.instant.desc': 'Use o mesmo programa em várias localizações ou junte negócios de uma rua, centro comercial ou bairro numa só experiência de fidelização.',
    'features.secure.title': 'Seguro e Confiável',
    'features.secure.desc': 'Dados protegidos com criptografia de nível bancário. Sistema confiável que garante a segurança das informações dos seus clientes e do seu negócio.',
    'features.cloud.title': 'Duas apps ligadas entre si',
    'features.cloud.desc': 'O seu negócio usa a app de gestão para selar e enviar campanhas. Os clientes usam a app de cliente para guardar todos os cartões no mesmo sítio',
    'features.team.title': 'Recompensas totalmente configuráveis',
    'features.team.desc': 'Escolha quantos selos são precisos, que prémio oferece e se há validade. Altere tudo em poucos toques, sem precisar de um técnico.',
    'features.formats.title': 'Promoções e lembretes automáticos',
    'features.formats.desc': 'Envie notificações para lembrar clientes de que estão quase a ganhar um prémio ou para anunciar campanhas especiais.',

    // Features Page
    'featuresPage.hero.title': 'Recursos Poderosos para Fluxos de Trabalho Modernos',
    'featuresPage.hero.subtitle': 'Tudo o que você precisa para digitalizar o seu processo de selagem de documentos. Projetado para eficiência, construído para escala.',
    'featuresPage.hero.docsDaily': 'Documentos Diariamente',
    'featuresPage.hero.uptime': 'SLA de Tempo de Atividade',
    'featuresPage.hero.customers': 'Clientes Satisfeitos',
    'featuresPage.allFeatures.title': 'Conjunto Completo de Recursos',
    'featuresPage.advanced.title': 'Personalização Avançada',
    'featuresPage.advanced.desc': 'Controle total sobre cores, fontes, tamanhos e opacidade. Crie selos que correspondam perfeitamente à identidade da sua marca.',
    'featuresPage.history.title': 'Histórico de Documentos',
    'featuresPage.history.desc': 'Rastreie todas as alterações e selos aplicados aos seus documentos. Trilha de auditoria completa para conformidade e responsabilidade.',
    'featuresPage.multilang.title': 'Suporte Multilíngue',
    'featuresPage.multilang.desc': 'Crie selos em qualquer idioma com suporte Unicode. Perfeito para empresas e documentos internacionais.',
    'featuresPage.tamperproof.title': 'Tecnologia à Prova de Adulteração',
    'featuresPage.tamperproof.desc': 'Marca d\'água digital e verificação garantem que seus documentos selados não possam ser alterados ou falsificados.',
    'featuresPage.mobile.title': 'Pronto para Mobile',
    'featuresPage.mobile.desc': 'Funcionalidade completa em dispositivos móveis. Sele documentos em movimento do seu telefone ou tablet.',
    'featuresPage.batch.title': 'Processamento em Lote',
    'featuresPage.batch.desc': 'Aplique selos em vários documentos de uma vez. Economize tempo com fluxos de trabalho e modelos automatizados.',
    'featuresPage.design.title': 'Projete Selos do Seu Jeito',
    'featuresPage.design.subtitle': 'Nosso designer de selos intuitivo lhe dá controle criativo completo. Faça upload de logotipos, adicione texto, ajuste cores e crie carimbos profissionais em minutos.',
    'featuresPage.design.feature1': 'Interface de arrastar e soltar para design fácil',
    'featuresPage.design.feature2': 'Mais de 100 modelos profissionais pré-projetados',
    'featuresPage.design.feature3': 'Importe os seus próprios gráficos e logotipos',
    'featuresPage.collab.title': 'Colabore Perfeitamente',
    'featuresPage.collab.subtitle': 'Construído para equipes de todos os tamanhos. Compartilhe selos, gerencie permissões e mantenha a consistência da marca em toda a sua organização.',
    'featuresPage.collab.feature1': 'Controle de acesso baseado em funções para membros da equipe',
    'featuresPage.collab.feature2': 'Colaboração em tempo real em documentos',
    'featuresPage.collab.feature3': 'Gerenciamento centralizado de biblioteca de selos',

    // Pricing
    'pricing.title': 'Preços Simples e Transparentes',
    'pricing.subtitle': 'Escolha o plano perfeito para as suas necessidades. Todos os planos incluem teste gratuito de 14 dias.',
    'pricing.benefit.cancel': 'Cancele a qualquer momento',
    'pricing.benefit.secure': 'Pagamento 100% seguro',
    'pricing.benefit.noFee': 'Sem taxas de configuração',
    'pricing.plan.free': 'Gratuito',
    'pricing.plan.starter': 'Iniciante',
    'pricing.plan.growth': 'Expansão',
    'pricing.plan.pro': 'Profissional',
    'pricing.plan.enterprise': 'Empresarial',
    'pricing.free.desc': 'Perfeito para indivíduos começando',
    'pricing.starter.desc': 'Ótimo para pequenos negócios',
    'pricing.growth.desc': 'Ideal para equipes em crescimento',
    'pricing.pro.desc': 'Para empresas estabelecidas',
    'pricing.enterprise.desc': 'Para grandes organizações',
    'pricing.mostPopular': 'Mais Popular',
    'pricing.month': 'mês',
    'pricing.custom': 'Personalizado',
    'pricing.cta.free': 'Começar Grátis',
    'pricing.cta.trial': 'Iniciar Teste Grátis',
    'pricing.cta.sales': 'Contactar Vendas',
    'pricing.feature.location1': '1 localização',
    'pricing.feature.locations3': 'Até 3 localizações',
    'pricing.feature.locations10': 'Até 10 localizações',
    'pricing.feature.locationsUnlimited': 'Localizações ilimitadas',
    'pricing.feature.unlimitedAll': 'Clientes, Carimbos, Funcionários & Dispositivos Ilimitados',
    'pricing.feature.emails1000': '1,000 emails/mês',
    'pricing.feature.emails3000': '3,000 emails/mês',
    'pricing.feature.emails10000': '10,000 emails/mês',
    'pricing.feature.emailsNegotiated': 'Emails negociados',
    'pricing.feature.pushUnlimited': 'Notificações push ilimitadas',
    'pricing.feature.groupNone': 'Sem fidelidade de grupo',
    'pricing.feature.group1': 'Participar ou criar 1 grupo',
    'pricing.feature.groupUnlimited': 'Grupos ilimitados',
    'pricing.feature.stamps5': '5 carimbos por mês',
    'pricing.feature.stamps100': '100 carimbos por mês',
    'pricing.feature.stampsUnlimited': 'Carimbos ilimitados',
    'pricing.feature.design1': '1 design de carimbo personalizado',
    'pricing.feature.design5': '5 designs de carimbo personalizados',
    'pricing.feature.designUnlimited': 'Designs personalizados ilimitados',
    'pricing.feature.templatesBasic': 'Modelos básicos',
    'pricing.feature.templatesPremium': 'Modelos premium',
    'pricing.feature.pdfSupport': 'Suporte a PDF',
    'pricing.feature.allFormats': 'Todos os formatos de arquivo',
    'pricing.feature.emailSupport': 'Suporte por e-mail',
    'pricing.feature.prioritySupport': 'Suporte prioritário',
    'pricing.feature.cloud5': 'Armazenamento na nuvem (5GB)',
    'pricing.feature.cloud50': 'Armazenamento na nuvem (50GB)',
    'pricing.feature.cloudUnlimited': 'Armazenamento na nuvem ilimitado',
    'pricing.feature.team3': 'Colaboração em equipe (3 usuários)',
    'pricing.feature.team15': 'Colaboração em equipe (15 usuários)',
    'pricing.feature.teamUnlimited': 'Membros de equipe ilimitados',
    'pricing.feature.customization': 'Personalização avançada',
    'pricing.feature.everything': 'Tudo no Profissional',
    'pricing.feature.api': 'Acesso à API',
    'pricing.feature.sso': 'Integração SSO',
    'pricing.feature.manager': 'Gerente de conta dedicado',
    'pricing.feature.branding': 'Marca personalizada',
    'pricing.feature.sla': 'Garantia SLA',
    'pricing.feature.priceOnRequest': 'Preço sob consulta',
    'pricing.monthly': 'Mensal',
    'pricing.annual': 'Anual',
    'pricing.saveUpTo': 'Poupe até 14%',
    'pricing.flexiblePlans': 'Planos Flexíveis',
    'pricing.year': 'ano',
    'pricing.featuresIncluded': 'Recursos incluídos:',
    'pricing.faq.title': 'Perguntas Frequentes',
    'pricing.faq.subtitle': 'Tire suas dúvidas sobre nossos planos e serviços',
    'pricing.faq.q1': 'Posso mudar de plano depois?',
    'pricing.faq.a1': 'Sim! Você pode fazer upgrade ou downgrade do seu plano a qualquer momento. As alterações entram em vigor imediatamente e faremos o rateio proporcional de quaisquer cobranças.',
    'pricing.faq.q2': 'Quais métodos de pagamento vocês aceitam?',
    'pricing.faq.a2': 'Aceitamos todos os principais cartões de crédito, PayPal e transferências bancárias para clientes Enterprise.',
    'pricing.faq.q3': 'Existe taxa de configuração?',
    'pricing.faq.a3': 'Nenhuma taxa de configuração para qualquer plano. Comece imediatamente sem custos ocultos.',
    'pricing.faq.q4': 'O que acontece após o término do meu teste?',
    'pricing.faq.a4': 'Seu teste é automaticamente convertido para o plano Grátis, a menos que você escolha um plano pago. Nenhum cartão de crédito é necessário para o teste.',

    // Blog
    'blog.title': 'Blog Stamply',
    'blog.subtitle': 'Insights, dicas e notícias sobre soluções de carimbos digitais e gerenciamento de documentos',
    'blog.search': 'Pesquisar artigos...',
    'blog.featured': 'Artigo em Destaque',
    'blog.allArticles': 'Todos os Artigos',
    'blog.readMore': 'Ler Mais',
    'blog.readFull': 'Ler Artigo Completo',
    'blog.viewAll': 'Ver Todas as Postagens',
    'blog.category.all': 'Todos',
    'blog.category.insights': 'Insights da Indústria',
    'blog.category.legal': 'Legal',
    'blog.category.productivity': 'Produtividade',
    'blog.category.tutorials': 'Tutoriais',
    'blog.category.news': 'Notícias da Empresa',
    'blog.newsletter.title': 'Inscreva-se na Nossa Newsletter',
    'blog.newsletter.subtitle': 'Receba os últimos artigos, insights e atualizações na sua caixa de entrada semanalmente.',
    'blog.newsletter.placeholder': 'Digite o seu e-mail',
    'blog.newsletter.cta': 'Inscrever-se',

    // Download
    'download.title': 'Baixar Stamply',
    'download.subtitle': 'Disponível em todas as suas plataformas favoritas. Escolha a versão que funciona melhor para você e comece a selar documentos digitalmente em minutos.',
    'download.cta.now': 'Baixar Agora',
    'download.cta.requirements': 'Ver Requisitos do Sistema',
    'download.choose': 'Escolha a sua plataforma',
    'download.chooseSubtitle': 'Stamply funciona perfeitamente em todos os dispositivos. Baixe uma vez, use em qualquer lugar com sincronização na nuvem.',
    'download.platform.desktop': 'App Desktop',
    'download.platform.ios': 'App iOS',
    'download.platform.android': 'App Android',
    'download.platform.web': 'App Web',
    'download.platform.chrome': 'Extensão Chrome',
    'download.platform.tablet': 'Tablet',
    'download.platform.windows': 'Windows',
    'download.platform.mac': 'macOS',
    'download.desc.windows': 'Para Windows 10 e posterior',
    'download.desc.mac': 'Para macOS 11.0 e posterior',
    'download.desc.ios': 'Para iPhone e iPad',
    'download.desc.android': 'Para dispositivos Android 8.0 e superior',
    'download.desc.web': 'Funciona em qualquer navegador moderno',
    'download.desc.chrome': 'Acesso rápido do seu navegador',
    'download.cta.windows': 'Baixar para Windows',
    'download.cta.mac': 'Baixar para Mac',
    'download.cta.appstore': 'Download na App Store',
    'download.cta.playstore': 'Download na Play Store',
    'download.cta.webapp': 'Iniciar App Web',
    'download.cta.addchrome': 'Adicionar ao Chrome',
    'download.version': 'Versão',
    'download.size': 'Tamanho',
    'download.noDownload': 'Sem download',
    'download.latest': 'Mais recente',

    // Contact
    'contact.title': 'Entre em Contacto',
    'contact.subtitle': 'Tem dúvidas sobre o Stamply? Estamos aqui para ajudar. Entre em contacto com a nossa equipa e responderemos o mais breve possível.',
    'contact.email': 'Envie-nos um E-mail',
    'contact.emailDesc': 'A nossa equipa normalmente responde em 24 horas',
    'contact.call': 'Ligue para Nós',
    'contact.callDesc': 'Seg-Sex das 9h às 18h PST',
    'contact.chat': 'Chat ao Vivo',
    'contact.chatDesc': 'Converse com a nossa equipa de suporte em tempo real',
    'contact.chatStart': 'Iniciar uma conversa',
    'contact.info': 'Informações de Contacto',
    'contact.form.title': 'Envie-nos uma Mensagem',
    'contact.form.name': 'Nome Completo',
    'contact.form.email': 'Endereço de E-mail',
    'contact.form.company': 'Empresa',
    'contact.form.phone': 'Número de Telefone',
    'contact.form.subject': 'Assunto',
    'contact.form.subject.select': 'Selecione um assunto',
    'contact.form.subject.sales': 'Consulta de Vendas',
    'contact.form.subject.support': 'Suporte Técnico',
    'contact.form.subject.billing': 'Questão de Cobrança',
    'contact.form.subject.feature': 'Solicitação de Recurso',
    'contact.form.subject.partnership': 'Oportunidade de Parceria',
    'contact.form.subject.other': 'Outro',
    'contact.form.message': 'Mensagem',
    'contact.form.messagePlaceholder': 'Diga-nos como podemos ajudá-lo...',
    'contact.form.send': 'Enviar Mensagem',
    'contact.form.required': '*',
    'contact.offices': 'Os Nossos Escritórios',
    'contact.offices.subtitle': 'Visite-nos em uma das nossas localizações globais',
    'contact.hours': 'Horário de Funcionamento',
    'contact.hours.weekday': 'Segunda - Sexta:',
    'contact.hours.saturday': 'Sábado:',
    'contact.hours.sunday': 'Domingo:',
    'contact.hours.weekdayTime': '9:00 - 18:00',
    'contact.hours.saturdayTime': '10:00 - 16:00',
    'contact.hours.closed': 'Fechado',
    'contact.hours.note': '* Horários em Hora do Pacífico (PST)',
    'contact.headquarters': 'Sede',
    'contact.global': 'Presença Global',
    'contact.globalDesc': 'Escritórios em 3 países\nSuporte a mais de 50 idiomas',

    // Get Started
    'getstarted.title': 'Comece com Stamply',
    'getstarted.subtitle': 'Junte-se a milhares de empresas transformando seu fluxo de trabalho de documentos. Inicie seu teste gratuito de 14 dias hoje.',
    'getstarted.benefit1.title': 'Configuração Rápida',
    'getstarted.benefit1.desc': 'Comece em menos de 5 minutos',
    'getstarted.benefit2.title': 'Teste Grátis de 14 Dias',
    'getstarted.benefit2.desc': 'Acesso completo a todos os recursos Profissionais',
    'getstarted.benefit3.title': 'Sem Cartão de Crédito',
    'getstarted.benefit3.desc': 'Comece grátis, atualize quando estiver pronto',
    'getstarted.steps.title': 'Três Passos Simples',
    'getstarted.step1.title': 'Crie A Sua Conta',
    'getstarted.step1.desc': 'Inscreva-se em segundos com o seu e-mail. Nenhum cartão de crédito necessário para o teste gratuito.',
    'getstarted.step2.title': 'Projete o seu Primeiro Selo',
    'getstarted.step2.desc': 'Escolha entre modelos ou crie um selo personalizado com o nosso designer intuitivo.',
    'getstarted.step3.title': 'Comece a Selar',
    'getstarted.step3.desc': 'Faça upload de documentos e aplique os seus selos instantaneamente. É simples assim!',
    'getstarted.form.title': 'Crie a sua Conta Gratuita',
    'getstarted.form.subtitle': 'Nenhum cartão de crédito necessário. Inicie o seu teste gratuito de 14 dias.',
    'getstarted.form.name': 'Nome Completo',
    'getstarted.form.email': 'E-mail de Trabalho',
    'getstarted.form.company': 'Nome da Empresa',
    'getstarted.form.teamSize': 'Tamanho da Equipa',
    'getstarted.form.teamSize.select': 'Selecione o tamanho da equipe',
    'getstarted.form.teamSize.1': 'Apenas eu',
    'getstarted.form.teamSize.2-10': '2-10 pessoas',
    'getstarted.form.teamSize.11-50': '11-50 pessoas',
    'getstarted.form.teamSize.51-200': '51-200 pessoas',
    'getstarted.form.teamSize.200+': '200+ pessoas',
    'getstarted.form.useCase': 'Para que você usará o Stamply?',
    'getstarted.form.useCase.select': 'Selecione o caso de uso',
    'getstarted.form.useCase.contracts': 'Aprovação de Contratos',
    'getstarted.form.useCase.invoices': 'Processamento de Faturas',
    'getstarted.form.useCase.legal': 'Documentos Legais',
    'getstarted.form.useCase.hr': 'Documentos de RH',
    'getstarted.form.useCase.general': 'Negócios em Geral',
    'getstarted.form.useCase.other': 'Outro',
    'getstarted.form.password': 'Senha',
    'getstarted.form.passwordPlaceholder': 'Crie uma senha segura',
    'getstarted.form.passwordHint': 'Deve ter pelo menos 8 caracteres',
    'getstarted.form.cta': 'Iniciar Teste Grátis',
    'getstarted.form.terms': 'Ao se inscrever, você concorda com nossos',
    'getstarted.form.termsLink': 'Termos de Serviço',
    'getstarted.form.and': 'e',
    'getstarted.form.privacyLink': 'Política de Privacidade',
    'getstarted.included.title': 'O Que Está Incluído no Seu Teste Grátis',
    'getstarted.included.1.title': 'Selos Ilimitados',
    'getstarted.included.1.desc': 'Crie e aplique selos digitais ilimitados nos seus documentos durante o período de teste.',
    'getstarted.included.2.title': 'Todos os Recursos Profissionais',
    'getstarted.included.2.desc': 'Acesse modelos premium, personalização avançada e ferramentas de colaboração em equipa.',
    'getstarted.included.3.title': 'Suporte Prioritário',
    'getstarted.included.3.desc': 'Obtenha ajuda da nossa equipa de suporte sempre que precisar por e-mail, chat ou telefone.',
    'getstarted.included.4.title': 'Armazenamento na Nuvem',
    'getstarted.included.4.desc': '50GB de armazenamento seguro na nuvem para todos os seus documentos e modelos carimbados.',
    'getstarted.included.5.title': 'Colaboração em Equipe',
    'getstarted.included.5.desc': 'Convide até 15 membros da equipa para colaborar em selos e documentos.',
    'getstarted.included.6.title': 'Sem Cartão de Crédito',
    'getstarted.included.6.desc': 'Inicie o seu teste sem nenhuma informação de pagamento. Atualize quando estiver pronto.',
    'getstarted.help.title': 'Precisa de Ajuda para Começar?',
    'getstarted.help.desc': 'A nossa equipa está pronta para ajudá-lo a configurar o Stamply e responder a quaisquer perguntas.',
    'getstarted.help.cta': 'Agendar uma Demonstração',
    'getstarted.trusted': 'Confiado por Empresas Líderes',
    'getstarted.testimonial': 'Stamply reduziu o nosso tempo de processamento de documentos em 80%. A configuração foi incrivelmente fácil e a nossa equipa começou a usar em minutos.',

    // Footer
    'footer.cta.title': 'Pronto para Digitalizar?',
    'footer.cta.subtitle': 'Junte-se a milhares de empresas que já usam Stamply para otimizar seu fluxo de trabalho de documentos.',
    'footer.cta.trial': 'Iniciar Teste Grátis',
    'footer.cta.sales': 'Falar com Vendas',
    'footer.product': 'Menu',
    'footer.integrations': 'Integrações',
    'footer.app': 'App',
    'footer.app.customerIOS': 'Customer iOS',
    'footer.app.customerAndroid': 'Customer Android',
    'footer.app.businessIOS': 'Business iOS',
    'footer.app.businessAndroid': 'Business Android',
    'footer.resources': 'Recursos',
    'footer.documentation': 'Documentação',
    'footer.api': 'Referência da API',
    'footer.help': 'Central de Ajuda',
    'footer.company': 'Empresa',
    'footer.about': 'Sobre Nós',
    'footer.careers': 'Carreiras',
    'footer.partners': 'Parceiros',
    'footer.copyright': '© 2025 Stamply. Todos os direitos reservados.',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Serviço',
    'footer.cookies': 'Política de Cookies',

    // Common
    'common.readTime': 'min de leitura',
    'common.author': 'Autor',
    'common.back': 'Voltar',

    // Select Plan
    'selectPlan.title': 'Escolha O Seu Plano',
    'selectPlan.subtitle': 'Selecione o plano perfeito para as suas necessidades e comece hoje mesmo.',
    'selectPlan.professional': 'Profissional',
    'selectPlan.business': 'Business',
    'selectPlan.enterprise': 'Empresarial',
    'selectPlan.starter': 'Iniciante',
    'selectPlan.growth': 'Expansão',
    'selectPlan.pro': 'Profissional',
    'selectPlan.unlimited': 'Ilimitado',
    'selectPlan.selectPlan': 'Selecionar Plano',
    'selectPlan.contact': 'Contactar',
    'selectPlan.perMonth': '/mês',
    'selectPlan.perYear': '/ano',
    'selectPlan.fromMonth': 'a partir de €99+/mês',
    'selectPlan.priceOnRequest': 'Preço sob consulta',
    'selectPlan.monthly': 'Mensal',
    'selectPlan.annual': 'Anual',
    'selectPlan.saveUpTo': 'Poupe até 14%',

    // Auth
    'auth.login': 'Iniciar Sessão',
    'auth.createAccount': 'Criar Conta',
    'auth.welcomeBack': 'Bem-vindo de volta ao Stamply',
    'auth.getStarted': 'Comece a sua jornada com o Stamply',
    'auth.fullName': 'Nome Completo',
    'auth.enterName': 'Digite o seu nome completo',
    'auth.email': 'Email',
    'auth.enterEmail': 'Digite o seu email',
    'auth.password': 'Palavra-passe',
    'auth.enterPassword': 'Digite a sua palavra-passe',
    'auth.forgotPassword': 'Esqueceu a palavra-passe?',
    'auth.agreeTerms': 'Concordo com os Termos de Serviço e Política de Privacidade',
    'auth.loginButton': 'Entrar',
    'auth.createAccountButton': 'Criar Conta',
    'auth.or': 'OU',
    'auth.continueWithGoogle': 'Continuar com Google',
    'auth.continueWithApple': 'Continuar com Apple',
    'auth.noAccount': 'Não tem uma conta?',
    'auth.haveAccount': 'Já tem uma conta?',
    'auth.signUpLink': 'Criar conta',
    'auth.loginLink': 'Iniciar sessão',
    'auth.success': 'Sucesso!',
    'auth.successMessage': 'Redirecionando para seleção de planos...',
    'auth.loading': 'Autenticando...',
    'auth.loadingMessage': 'Por favor aguarde um momento',

    // Checkout
    'checkout.title': 'Finalizar Assinatura',
    'checkout.subtitle': 'Último passo para ativar sua conta Stamply',
    'checkout.billingInfo': 'Informações de Faturação',
    'checkout.billingInfoDesc': 'Informações de faturação',
    'checkout.fullName': 'Nome Completo',
    'checkout.country': 'País',
    'checkout.postalCode': 'Código Postal',
    'checkout.address': 'Endereço',
    'checkout.businessPurchase': 'Compra para empresa',
    'checkout.businessPurchaseDesc': 'Para empresas e organizações',
    'checkout.businessName': 'Nome da Empresa',
    'checkout.vatNumber': 'Número de IVA',
    'checkout.vatCountry': 'País do IVA',
    'checkout.email': 'Email',
    'checkout.contact': 'Contacto',
    'checkout.contactDesc': 'Onde enviaremos as confirmações',
    'checkout.paymentMethod': 'Método de Pagamento',
    'checkout.cardNumber': 'Número do Cartão',
    'checkout.expiryDate': 'Validade',
    'checkout.cardDetails': 'Detalhes do Cartão',
    'checkout.subscribe': 'Finalizar Assinatura',
    'checkout.locations': 'Localizações',
    'checkout.locationsDesc': 'Quantas lojas você possui?',
    'checkout.location': 'localização',
    'checkout.locationsPlural': 'localizações',
    'checkout.summary': 'Resumo da Assinatura',
    'checkout.plan': 'Plano',
    'checkout.locationsCount': 'x Localizações',
    'checkout.vat': 'IVA (23%)',
    'checkout.totalMonthly': 'Total mensal',
    'checkout.totalAnnual': 'Total anual',
    'checkout.included': 'Incluído no seu plano:',
    'checkout.unlimitedStamps': 'Carimbos ilimitados',
    'checkout.unlimitedPush': 'Push notifications ilimitadas',
    'checkout.prioritySupport': 'Suporte prioritário',
    'checkout.cancelAnytime': 'Cancelamento a qualquer momento',
    'checkout.securePayment': 'Pagamento seguro via Stripe',
    'checkout.fullNamePlaceholder': 'João Silva',
    'checkout.postalCodePlaceholder': '1000-001',
    'checkout.addressPlaceholder': 'Rua Example, 123',
    'checkout.businessNamePlaceholder': 'Nome da Empresa Lda.',
    'checkout.vatNumberPlaceholder': 'PT123456789',
    'checkout.emailPlaceholder': 'seu@email.com',
    'checkout.processing': 'Processando...',
    'checkout.secureBadge': 'Pagamentos seguros processados pelo Stripe',
    'checkout.errorOccurred': 'Ocorreu um erro',

    // Additional
    'selectPlan.allPlansInclude': 'Todos os planos incluem acesso total a recursos ilimitados de clientes, carimbos, funcionários e dispositivos',
  },
  en: {
    // Navbar
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.blog': 'Blog',
    'nav.download': 'Download',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',
    'nav.guide': 'Quick Guide',

    // Hero
    'hero.badge': 'Digital Stamp Solution',
    'hero.title': 'Stamp your business',
    'hero.subtitle': 'Transform your workflow with our powerful online stamp solution. Create, customize, and apply digital stamps to any document instantly.',
    'hero.benefit1': 'Legally binding electronic stamps',
    'hero.benefit2': 'Custom stamp designs & templates',
    'hero.benefit3': 'Secure cloud storage for all documents',
    'hero.cta.start': 'Get Started Free',
    'hero.cta.download': 'Download App',
    'hero.stats': 'Documents Stamped Daily',

    // Features
    'features.title': 'Everything You Need to Stamp Digitally',
    'features.subtitle': 'Powerful features designed to optimize your loyalty program and increase customer engagement.',
    'features.custom.title': 'Digital stamps in seconds',
    'features.custom.desc': 'The customer shows a QR code on their phone, the staff points the camera, and the stamp is registered automatically.',
    'features.instant.title': 'Multiple locations and groups',
    'features.instant.desc': 'Use the same loyalty program across several locations, or bring together businesses on the same street, shopping centre, or neighbourhood in a single experience.',
    'features.secure.title': 'Secure & Reliable',
    'features.secure.desc': 'Data protected with bank-level encryption. A reliable system that ensures the security of your customers\' information and your business.',
    'features.cloud.title': 'One app for businesses, another for customers',
    'features.cloud.desc': 'Your business uses the management app to stamp and send campaigns. Customers use the customer app to keep all their loyalty cards in one place.',
    'features.team.title': 'Rewards tailored to your business',
    'features.team.desc': 'Choose how many stamps are needed, what reward you offer, and if it expires. Change everything in a few taps, without needing a technician.',
    'features.formats.title': 'Smart promotions and reminders',
    'features.formats.desc': 'Send notifications to remind customers they’re close to a reward or to announce special campaigns.',

    // Features Page
    'featuresPage.hero.title': 'Powerful Features for Modern Workflows',
    'featuresPage.hero.subtitle': 'Everything you need to digitize your document stamping process. Designed for efficiency, built for scale.',
    'featuresPage.hero.docsDaily': 'Documents Daily',
    'featuresPage.hero.uptime': 'Uptime SLA',
    'featuresPage.hero.customers': 'Satisfied Customers',
    'featuresPage.allFeatures.title': 'Complete Feature Set',
    'featuresPage.advanced.title': 'Advanced Customization',
    'featuresPage.advanced.desc': 'Full control over colors, fonts, sizes, and opacity. Create stamps that perfectly match your brand identity.',
    'featuresPage.history.title': 'Document History',
    'featuresPage.history.desc': 'Track all changes and stamps applied to your documents. Complete audit trail for compliance and accountability.',
    'featuresPage.multilang.title': 'Multilingual Support',
    'featuresPage.multilang.desc': 'Create stamps in any language with Unicode support. Perfect for international businesses and documents.',
    'featuresPage.tamperproof.title': 'Tamper-Proof Technology',
    'featuresPage.tamperproof.desc': 'Digital watermarking and verification ensure your stamped documents cannot be altered or forged.',
    'featuresPage.mobile.title': 'Ready for Mobile',
    'featuresPage.mobile.desc': 'Full functionality on mobile devices. Stamp documents on the go from your phone or tablet.',
    'featuresPage.batch.title': 'Batch Processing',
    'featuresPage.batch.desc': 'Apply stamps to multiple documents at once. Save time with automated workflows and templates.',
    'featuresPage.design.title': 'Design Stamps Your Way',
    'featuresPage.design.subtitle': 'Our intuitive stamp designer gives you complete creative control. Upload logos, add text, adjust colors, and create professional stamps in minutes.',
    'featuresPage.design.feature1': 'Drag-and-drop interface for easy design',
    'featuresPage.design.feature2': 'Over 100 pre-designed professional templates',
    'featuresPage.design.feature3': 'Import your own graphics and logos',
    'featuresPage.collab.title': 'Collaborate Perfectly',
    'featuresPage.collab.subtitle': 'Built for teams of all sizes. Share stamps, manage permissions, and maintain brand consistency across your organization.',
    'featuresPage.collab.feature1': 'Role-based access control for team members',
    'featuresPage.collab.feature2': 'Real-time collaboration on documents',
    'featuresPage.collab.feature3': 'Centralized stamp library management',

    // Pricing
    'pricing.title': 'Simple, Transparent Pricing',
    'pricing.subtitle': 'Choose the perfect plan for your needs. All plans include a 14-day free trial.',
    'pricing.benefit.cancel': 'Cancel anytime',
    'pricing.benefit.secure': '100% secure payment',
    'pricing.benefit.noFee': 'No setup fees',
    'pricing.plan.free': 'Free',
    'pricing.plan.starter': 'Starter',
    'pricing.plan.growth': 'Growth',
    'pricing.plan.pro': 'Pro',
    'pricing.plan.enterprise': 'Enterprise',
    'pricing.free.desc': 'Perfect for individuals getting started',
    'pricing.starter.desc': 'Great for small businesses',
    'pricing.growth.desc': 'Ideal for growing teams',
    'pricing.pro.desc': 'For established companies',
    'pricing.enterprise.desc': 'For large organizations',
    'pricing.mostPopular': 'Most Popular',
    'pricing.month': 'month',
    'pricing.custom': 'Custom',
    'pricing.cta.free': 'Start Free',
    'pricing.cta.trial': 'Start Free Trial',
    'pricing.cta.sales': 'Contact Sales',
    'pricing.feature.location1': '1 location',
    'pricing.feature.locations3': 'Up to 3 locations',
    'pricing.feature.locations10': 'Up to 10 locations',
    'pricing.feature.locationsUnlimited': 'Unlimited locations',
    'pricing.feature.unlimitedAll': 'Unlimited Customers, Stamps, Employees & Devices',
    'pricing.feature.emails1000': '1,000 emails/month',
    'pricing.feature.emails3000': '3,000 emails/month',
    'pricing.feature.emails10000': '10,000 emails/month',
    'pricing.feature.emailsNegotiated': 'Negotiated emails',
    'pricing.feature.pushUnlimited': 'Unlimited push notifications',
    'pricing.feature.groupNone': 'No group loyalty',
    'pricing.feature.group1': 'Join or create 1 group',
    'pricing.feature.groupUnlimited': 'Unlimited groups',
    'pricing.feature.stamps5': '5 stamps per month',
    'pricing.feature.stamps100': '100 stamps per month',
    'pricing.feature.stampsUnlimited': 'Unlimited stamps',
    'pricing.feature.design1': '1 custom stamp design',
    'pricing.feature.design5': '5 custom stamp designs',
    'pricing.feature.designUnlimited': 'Unlimited custom designs',
    'pricing.feature.templatesBasic': 'Basic templates',
    'pricing.feature.templatesPremium': 'Premium templates',
    'pricing.feature.pdfSupport': 'PDF support',
    'pricing.feature.allFormats': 'All file formats',
    'pricing.feature.emailSupport': 'Email support',
    'pricing.feature.prioritySupport': 'Priority support',
    'pricing.feature.cloud5': 'Cloud storage (5GB)',
    'pricing.feature.cloud50': 'Cloud storage (50GB)',
    'pricing.feature.cloudUnlimited': 'Unlimited cloud storage',
    'pricing.feature.team3': 'Team collaboration (3 users)',
    'pricing.feature.team15': 'Team collaboration (15 users)',
    'pricing.feature.teamUnlimited': 'Unlimited team members',
    'pricing.feature.customization': 'Advanced customization',
    'pricing.feature.everything': 'Everything in Professional',
    'pricing.feature.api': 'API access',
    'pricing.feature.sso': 'SSO integration',
    'pricing.feature.manager': 'Dedicated account manager',
    'pricing.feature.branding': 'Custom branding',
    'pricing.feature.sla': 'SLA guarantee',
    'pricing.feature.priceOnRequest': 'Price on request',
    'pricing.monthly': 'Monthly',
    'pricing.annual': 'Annual',
    'pricing.saveUpTo': 'Save up to 14%',
    'pricing.flexiblePlans': 'Flexible Plans',
    'pricing.year': 'year',
    'pricing.featuresIncluded': 'Included features:',
    'pricing.faq.title': 'Frequently Asked Questions',
    'pricing.faq.subtitle': 'Get answers to your questions about our plans and services',
    'pricing.faq.q1': 'Can I change my plan later?',
    'pricing.faq.a1': 'Yes! You can upgrade or downgrade your plan at any time. Changes take effect immediately and we\'ll prorate any charges proportionally.',
    'pricing.faq.q2': 'What payment methods do you accept?',
    'pricing.faq.a2': 'We accept all major credit cards, PayPal, and bank transfers for Enterprise customers.',
    'pricing.faq.q3': 'Is there a setup fee?',
    'pricing.faq.a3': 'No setup fees for any plan. Get started immediately with no hidden costs.',
    'pricing.faq.q4': 'What happens after my trial ends?',
    'pricing.faq.a4': 'Your trial automatically converts to the Free plan unless you choose a paid plan. No credit card required for the trial.',

    // Blog
    'blog.title': 'Stamply Blog',
    'blog.subtitle': 'Insights, tips, and news about digital stamp solutions and document management',
    'blog.search': 'Search articles...',
    'blog.featured': 'Featured',
    'blog.allArticles': 'All Articles',
    'blog.readMore': 'Read More',
    'blog.readFull': 'Read Full Article',
    'blog.viewAll': 'View All Posts',
    'blog.category.all': 'All',
    'blog.category.insights': 'Industry Insights',
    'blog.category.legal': 'Legal',
    'blog.category.productivity': 'Productivity',
    'blog.category.tutorials': 'Tutorials',
    'blog.category.news': 'Company News',
    'blog.newsletter.title': 'Subscribe to Our Newsletter',
    'blog.newsletter.subtitle': 'Get the latest articles, insights, and updates delivered to your inbox weekly.',
    'blog.newsletter.placeholder': 'Enter your email',
    'blog.newsletter.cta': 'Subscribe',

    // Download
    'download.title': 'Download Stamply',
    'download.subtitle': 'Available on all your favorite platforms. Choose the version that works best for you and start stamping documents digitally in minutes.',
    'download.cta.now': 'Download Now',
    'download.cta.requirements': 'View System Requirements',
    'download.choose': 'Choose Your Platform',
    'download.chooseSubtitle': 'Stamply works seamlessly across all devices. Download once, use everywhere with cloud sync.',
    'download.platform.desktop': 'Desktop App',
    'download.platform.ios': 'iOS App',
    'download.platform.android': 'Android App',
    'download.platform.web': 'Web App',
    'download.platform.chrome': 'Chrome Extension',
    'download.platform.tablet': 'Tablet',
    'download.platform.windows': 'Windows',
    'download.platform.mac': 'macOS',
    'download.desc.windows': 'For Windows 10 and later',
    'download.desc.mac': 'For macOS 11.0 and later',
    'download.desc.ios': 'For iPhone and iPad',
    'download.desc.android': 'For Android 8.0 and up',
    'download.desc.web': 'Works in any modern browser',
    'download.desc.chrome': 'Quick access from your browser',
    'download.cta.windows': 'Download for Windows',
    'download.cta.mac': 'Download for Mac',
    'download.cta.appstore': 'Download on App Store',
    'download.cta.playstore': 'Get it on Google Play',
    'download.cta.webapp': 'Launch Web App',
    'download.cta.addchrome': 'Add to Chrome',
    'download.version': 'Version',
    'download.size': 'Size',
    'download.noDownload': 'No download',
    'download.latest': 'Latest',

    // Contact
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Have questions about Stamply? We\'re here to help. Reach out to our team and we\'ll respond as soon as possible.',
    'contact.email': 'Email Us',
    'contact.emailDesc': 'Our team typically responds within 24 hours',
    'contact.call': 'Call Us',
    'contact.callDesc': 'Mon-Fri from 9am to 6pm PST',
    'contact.chat': 'Live Chat',
    'contact.chatDesc': 'Chat with our support team in real-time',
    'contact.chatStart': 'Start a conversation',
    'contact.info': 'Contact Information',
    'contact.form.title': 'Send Us a Message',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.company': 'Company',
    'contact.form.phone': 'Phone Number',
    'contact.form.subject': 'Subject',
    'contact.form.subject.select': 'Select a subject',
    'contact.form.subject.sales': 'Sales Inquiry',
    'contact.form.subject.support': 'Technical Support',
    'contact.form.subject.billing': 'Billing Question',
    'contact.form.subject.feature': 'Feature Request',
    'contact.form.subject.partnership': 'Partnership Opportunity',
    'contact.form.subject.other': 'Other',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Tell us how we can help you...',
    'contact.form.send': 'Send Message',
    'contact.form.required': '*',
    'contact.offices': 'Our Offices',
    'contact.offices.subtitle': 'Visit us at one of our global locations',
    'contact.hours': 'Business Hours',
    'contact.hours.weekday': 'Monday - Friday:',
    'contact.hours.saturday': 'Saturday:',
    'contact.hours.sunday': 'Sunday:',
    'contact.hours.weekdayTime': '9:00 AM - 6:00 PM',
    'contact.hours.saturdayTime': '10:00 AM - 4:00 PM',
    'contact.hours.closed': 'Closed',
    'contact.hours.note': '* Times are in Pacific Standard Time (PST)',
    'contact.headquarters': 'Headquarters',
    'contact.global': 'Global Presence',
    'contact.globalDesc': 'Offices in 3 countries\nSupporting 50+ languages',

    // Get Started
    'getstarted.title': 'Get Started with Stamply',
    'getstarted.subtitle': 'Join thousands of businesses transforming their document workflow. Start your free 14-day trial today.',
    'getstarted.benefit1.title': 'Quick Setup',
    'getstarted.benefit1.desc': 'Get up and running in under 5 minutes',
    'getstarted.benefit2.title': '14-Day Free Trial',
    'getstarted.benefit2.desc': 'Full access to all Professional features',
    'getstarted.benefit3.title': 'No Credit Card',
    'getstarted.benefit3.desc': 'Start free, upgrade when you\'re ready',
    'getstarted.steps.title': 'Three Simple Steps',
    'getstarted.step1.title': 'Create Your Account',
    'getstarted.step1.desc': 'Sign up in seconds with your email. No credit card required for the free trial.',
    'getstarted.step2.title': 'Design Your First Stamp',
    'getstarted.step2.desc': 'Choose from templates or create a custom stamp with our intuitive designer.',
    'getstarted.step3.title': 'Start Stamping',
    'getstarted.step3.desc': 'Upload documents and apply your stamps instantly. It\'s that simple!',
    'getstarted.form.title': 'Create Your Free Account',
    'getstarted.form.subtitle': 'No credit card required. Start your 14-day free trial.',
    'getstarted.form.name': 'Full Name',
    'getstarted.form.email': 'Work Email',
    'getstarted.form.company': 'Company Name',
    'getstarted.form.teamSize': 'Team Size',
    'getstarted.form.teamSize.select': 'Select team size',
    'getstarted.form.teamSize.1': 'Just me',
    'getstarted.form.teamSize.2-10': '2-10 people',
    'getstarted.form.teamSize.11-50': '11-50 people',
    'getstarted.form.teamSize.51-200': '51-200 people',
    'getstarted.form.teamSize.200+': '200+ people',
    'getstarted.form.useCase': 'What will you use Stamply for?',
    'getstarted.form.useCase.select': 'Select use case',
    'getstarted.form.useCase.contracts': 'Contract Approval',
    'getstarted.form.useCase.invoices': 'Invoice Processing',
    'getstarted.form.useCase.legal': 'Legal Documents',
    'getstarted.form.useCase.hr': 'HR Documents',
    'getstarted.form.useCase.general': 'General Business',
    'getstarted.form.useCase.other': 'Other',
    'getstarted.form.password': 'Password',
    'getstarted.form.passwordPlaceholder': 'Create a secure password',
    'getstarted.form.passwordHint': 'Must be at least 8 characters',
    'getstarted.form.cta': 'Start Free Trial',
    'getstarted.form.terms': 'By signing up, you agree to our',
    'getstarted.form.termsLink': 'Terms of Service',
    'getstarted.form.and': 'and',
    'getstarted.form.privacyLink': 'Privacy Policy',
    'getstarted.included.title': 'What\'s Included in Your Free Trial',
    'getstarted.included.1.title': 'Unlimited Stamps',
    'getstarted.included.1.desc': 'Create and apply unlimited digital stamps to your documents during your trial period.',
    'getstarted.included.2.title': 'All Professional Features',
    'getstarted.included.2.desc': 'Access premium templates, advanced customization, and team collaboration tools.',
    'getstarted.included.3.title': 'Priority Support',
    'getstarted.included.3.desc': 'Get help from our support team whenever you need it via email, chat, or phone.',
    'getstarted.included.4.title': 'Cloud Storage',
    'getstarted.included.4.desc': '50GB of secure cloud storage for all your stamped documents and templates.',
    'getstarted.included.5.title': 'Team Collaboration',
    'getstarted.included.5.desc': 'Invite up to 15 team members to collaborate on stamps and documents.',
    'getstarted.included.6.title': 'No Credit Card Required',
    'getstarted.included.6.desc': 'Start your trial without any payment information. Upgrade when you\'re ready.',
    'getstarted.help.title': 'Need Help Getting Started?',
    'getstarted.help.desc': 'Our team is ready to help you set up Stamply and answer any questions.',
    'getstarted.help.cta': 'Schedule a Demo',
    'getstarted.trusted': 'Trusted by Leading Companies',
    'getstarted.testimonial': 'Stamply reduced our document processing time by 80%. The setup was incredibly easy, and our team was up and running within minutes.',

    // Footer
    'footer.cta.title': 'Ready to Go Digital?',
    'footer.cta.subtitle': 'Join thousands of businesses already using Stamply to streamline their document workflow.',
    'footer.cta.trial': 'Start Free Trial',
    'footer.cta.sales': 'Talk to Sales',
    'footer.product': 'Product',
    'footer.integrations': 'Integrations',
    'footer.app': 'App',
    'footer.app.customerIOS': 'Customer iOS',
    'footer.app.customerAndroid': 'Customer Android',
    'footer.app.businessIOS': 'Business iOS',
    'footer.app.businessAndroid': 'Business Android',
    'footer.resources': 'Resources',
    'footer.documentation': 'Documentation',
    'footer.api': 'API Reference',
    'footer.help': 'Help Center',
    'footer.company': 'Company',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.partners': 'Partners',
    'footer.copyright': '© 2025 Stamply. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',

    // Common
    'common.readTime': 'min read',
    'common.author': 'Author',
    'common.back': 'Back',

    // Select Plan
    'selectPlan.title': 'Choose Your Plan',
    'selectPlan.subtitle': 'Select the perfect plan for your needs and start today.',
    'selectPlan.professional': 'Professional',
    'selectPlan.business': 'Business',
    'selectPlan.enterprise': 'Enterprise',
    'selectPlan.starter': 'Starter',
    'selectPlan.growth': 'Growth',
    'selectPlan.pro': 'Pro',
    'selectPlan.unlimited': 'Unlimited',
    'selectPlan.selectPlan': 'Select Plan',
    'selectPlan.contact': 'Contact',
    'selectPlan.perMonth': '/month',
    'selectPlan.perYear': '/year',
    'selectPlan.fromMonth': 'from €99+/month',
    'selectPlan.priceOnRequest': 'Price on request',
    'selectPlan.monthly': 'Monthly',
    'selectPlan.annual': 'Annual',
    'selectPlan.saveUpTo': 'Save up to 14%',

    // Auth
    'auth.login': 'Login',
    'auth.createAccount': 'Create Account',
    'auth.welcomeBack': 'Welcome back to Stamply',
    'auth.getStarted': 'Start your journey with Stamply',
    'auth.fullName': 'Full Name',
    'auth.enterName': 'Enter your full name',
    'auth.email': 'Email',
    'auth.enterEmail': 'Enter your email',
    'auth.password': 'Password',
    'auth.enterPassword': 'Enter your password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.agreeTerms': 'I agree to the Terms of Service and Privacy Policy',
    'auth.loginButton': 'Login',
    'auth.createAccountButton': 'Create Account',
    'auth.or': 'OR',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.continueWithApple': 'Continue with Apple',
    'auth.continueWithGithub': 'Continue with Github',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.haveAccount': 'Already have an account?',
    'auth.signUpLink': 'Sign up',
    'auth.loginLink': 'Log in',
    'auth.success': 'Success!',
    'auth.successMessage': 'Redirecting to plan selection...',
    'auth.loading': 'Authenticating...',
    'auth.loadingMessage': 'Please wait a moment',

    // Checkout
    'checkout.title': 'Finalize Subscription',
    'checkout.subtitle': 'Last step to activate your Stamply account',
    'checkout.billingInfo': 'Billing Information',
    'checkout.billingInfoDesc': 'Billing information',
    'checkout.fullName': 'Full Name',
    'checkout.country': 'Country',
    'checkout.postalCode': 'Postal Code',
    'checkout.address': 'Address',
    'checkout.businessPurchase': 'Business Purchase',
    'checkout.businessPurchaseDesc': 'For businesses and organizations',
    'checkout.businessName': 'Business Name',
    'checkout.vatNumber': 'VAT Number',
    'checkout.vatCountry': 'VAT Country',
    'checkout.email': 'Email',
    'checkout.contact': 'Contact',
    'checkout.contactDesc': 'Where we\'ll send confirmations',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.cardNumber': 'Card Number',
    'checkout.expiryDate': 'Expiry Date',
    'checkout.cardDetails': 'Card Details',
    'checkout.subscribe': 'Subscribe',
    'checkout.locations': 'Locations',
    'checkout.locationsDesc': 'How many stores do you have?',
    'checkout.location': 'location',
    'checkout.locationsPlural': 'locations',
    'checkout.summary': 'Subscription Summary',
    'checkout.plan': 'Plan',
    'checkout.locationsCount': 'x Locations',
    'checkout.vat': 'VAT (23%)',
    'checkout.totalMonthly': 'Monthly total',
    'checkout.totalAnnual': 'Annual total',
    'checkout.included': 'Included in your plan:',
    'checkout.unlimitedStamps': 'Unlimited stamps',
    'checkout.unlimitedPush': 'Unlimited push notifications',
    'checkout.prioritySupport': 'Priority support',
    'checkout.cancelAnytime': 'Cancel anytime',
    'checkout.securePayment': 'Secure payment via Stripe',
    'checkout.fullNamePlaceholder': 'John Doe',
    'checkout.postalCodePlaceholder': '12345',
    'checkout.addressPlaceholder': '123 Main Street',
    'checkout.businessNamePlaceholder': 'Company Name Ltd.',
    'checkout.vatNumberPlaceholder': 'GB123456789',
    'checkout.emailPlaceholder': 'your@email.com',
    'checkout.processing': 'Processing...',
    'checkout.secureBadge': 'Secure payments processed by Stripe',
    'checkout.errorOccurred': 'An error occurred',

    // Additional
    'selectPlan.allPlansInclude': 'All plans include full access to unlimited customers, stamps, employees and devices',
  },
};